title: Mourtada Houari
email: imadhou00@gmail.com
github_username: imadhou
linkedin_username: imadhou
instagram_username: mr_td.213
logo: /assets/img/profile-pic.png
description: >- # 
 ğŸ’» IngÃ©nieur en Big Data & DÃ©veloppeur Fullstack 
 ğŸ¯ PassionnÃ© par l'IA et les nouvelles technologies
 Radical dans ma mÃ©thodologie, jâ€™aime construire des solutions from scratch, tout en restant pragmatique pour Ã©viter de rÃ©inventer la roue. Mon quotidien est rythmÃ© par lâ€™Ã©criture de code, lâ€™exploration des avancÃ©es technologiques, et le partage de connaissances.
 Je suis animÃ© par un objectif ambitieux : implÃ©menter tous les types de rÃ©seaux de neurones artificiels from scratch. Cela me permet non seulement de dÃ©velopper une comprÃ©hension approfondie des thÃ©ories en IA, mais aussi dâ€™aider les autres Ã  contextualiser et maÃ®triser ces concepts complexes.
 Si vous partagez cet intÃ©rÃªt pour lâ€™IA, la programmation ou lâ€™apprentissage collaboratif, je serai ravi dâ€™Ã©changerâ€¯! ğŸš€"
show_downloads: true
theme: jekyll-theme-minimal
